[package]
name = "postgres-proxy-server"
version = "0.1.0"
edition = "2021"

[dependencies]
async-trait = "0.1.82"
chrono = "0.4.38"
futures = "0.3.30"
pgwire = "0.24.1"
tokio = { version = "1.40.0", features = ["full"] }
tokio-postgres = "0.7.11"
